version: '3.8'
services:
  popisfilms:
    container_name: popisfilms
    privileged: true
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    # env_file:
    #   - .env.development
    ports:
      - '3000:3000'
      - '8080:8080'
