version: '3.8'
services:
  movieland_app_local_client:
    container_name: popisfilms_app_local_client
    privileged: true
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
    # env_file:
    #   - .env.development
    ports:
      - '3000:3000'

  movieland_app_local_server:
    container_name: popisfilms_app_local_server
    privileged: true
    working_dir: /app
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
