name: Deploy Frontend to Firebase Hosting on push to Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
    steps:
      - uses: actions/checkout@v2
      - env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: echo $FIREBASE_CREDENTIALS > src/webapp/credentials.js
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIELAND_D92B1 }}'
          projectId: movieland-d92b1
          channelId: 'live'

